% This file was automatically generated by the LLM system
%%%%%%%%%%%%%%%%%%%%%%%
% kb
%%%%%%%%%%%%%%%%%%%%%%%
% Positions
pos(2,2).
pos(4,4).
pos(8,8).
pos(1,1).
pos(3,3).
pos(5,5).
pos(6,6).
pos(7,7).
pos(9,9).
pos(10,10).

% Blocks
block(b1).
block(b2).
block(b3).
block(b4).
block(b5).
block(b6).
block(b7).

% Agents
agent(a1).
agent(a2).
agent(a3).
agent(a4).
agent(a5).
agent(a6).
agent(a7).
agent(a8).

% Resources
resources(agent(_)).

%%%%%%%%%%%%%%%%%%%%%%%
% init
%%%%%%%%%%%%%%%%%%%%%%%
init_state([
  ontable(b1), ontable(b2), ontable(b4), ontable(b6), ontable(b7),
  on(b5, b1), on(b3, b2), 
  at(b1,2,2), at(b2,4,4), at(b4,8,8), at(b5,2,2), at(b3,4,4), at(b6,1,1), at(b7,3,3),
  clear(b5), clear(b3), clear(b4), clear(b6), clear(b7),
  available(a1), available(a2), available(a3), available(a4), available(a5), available(a6), available(a7), available(a8)
]).

%%%%%%%%%%%%%%%%%%%%%%%
% goal
%%%%%%%%%%%%%%%%%%%%%%%
goal_state([
  ontable(b1), ontable(b2), ontable(b4), ontable(b6), ontable(b7),
  on(b5, b4), on(b3, b2),
  at(b1,2,2), at(b2,4,4), at(b3,4,4), at(b4,8,8), at(b5,8,8), at(b6,1,1), at(b7,3,3),
  clear(b1), clear(b3), clear(b5), clear(b6), clear(b7),
  available(a1), available(a2), available(a3), available(a4), available(a5), available(a6), available(a7), available(a8)
]).

:- ensure_loaded('prolog_planner/examples/blocks_world/actions.pl').
:- ensure_loaded('prolog_planner/examples/blocks_world/mappings.pl').
